### PR TITLE
(fix #907) Trim query when searching for entities

### LINKED ISSUE #907: Trim query when searching for entities
If you [search for strings or strings+entities](https://transvision.mozfr.org/?recherche=+test&repo=gecko_strings&sourcelocale=en-US&locale=it&search_type=strings), and have extra spaces in the query, you get a warning and a link to search without spaces.

That doesn't happen on the "entities" search, and that's bad, since a search with spaces will basically always fail for entities.

We should trim the search query.

### PR DESCRIPTION
**Pull request by flodolo**
Also clean up code, using class method instead of a variable defined in a random include.

### CODE REVIEW

**Comment by TheoChevalier** [comment]
Since we’re actively trimming the query (compared to String search where we just warn), we may want to update the value in the search field. Just a suggestion, it’s looking good as it is

File: app/controllers/mainsearch.php [hunk 1]
```diff
@@ -54,6 +54,17 @@
...
 }
 
+/*
+    Trim the search query when searching for entities, display a warning.
+    This needs to be done before including search_form.php, in order to
+    display the trimmed value in the search field.
+*/
+if ($search->getSearchType() == 'entities' &&
+    $search->getSearchTerms() !== trim($search->getSearchTerms())) {
+    $search->setSearchTerms(trim($search->getSearchTerms()));
```
Comment (flodolo) [inline app/controllers/mainsearch.php]: I guess Atom's autocomplete here failed me, and it was using `setRegexSearchTerms` before.

File: app/views/results_entities.php [hunk 2]
```diff
@@ -225,7 +225,7 @@
 if ($entities) {
     $message_count = $real_search_results > $limit_results
         ? "<span class=\"results_count_{$search_id}\">{$limit_results} results</span> out of {$real_search_results}"
-        : "<span class=\"results_count_{$search_id}\">" . Utils::pluralize(count($search_results), 'result') . '</span>';
+        : "<span class=\"results_count_{$search_id}\">" . Utils::pluralize(count($real_search_results), 'result') . '</span>';
```
Comment (flodolo) [inline app/views/results_entities.php]: Poor copy and paste: `$search_results` is not defined in this view.
