### PR TITLE
Fix broken search results highlighting

### LINKED ISSUE #715: Highlight of match in results does not work properly
I noticed that a perfect match in the results isn't highlighted correct.

See https://transvision.mozfr.org/?recherche=+Add+a+Search+Engine&repo= Add a Search Engine aurora&sourcelocale=en-US&locale=da&search_type=strings

Some of the chars in 'Add a Search Engine' is not highlighted.

### PR DESCRIPTION
**Pull request by flodolo**
Fix #715

### CODE REVIEW

File: app/classes/Transvision/Utils.php [hunk 1]
```diff
@@ -119,8 +119,9 @@ public static function markString($needle, $haystack)
      */
     public static function highlightString($str)
     {
+        // See http://stackoverflow.com/a/14952740 for the regex background
         $str = preg_replace(
-            '/←(.*)→/isU',
+            '/←((?:[^←→]|(?R))*)→/isu',
```
Comment (flodolo) [inline app/classes/Transvision/Utils.php]: On second thoughts we should be able to drop also the 's' [modifier](http://php.net/manual/en/reference.pcre.pattern.modifiers.php). And probably worth adding a better explanation than a link to SO.
