### PR TITLE
Use https for translation links, fix http links in readme

### LINKED ISSUE #815: Translation links still use http

### PR DESCRIPTION
**Pull request by flodolo**
Fixes #815

### CODE REVIEW

File: app/views/results_entities.php [hunk 1]
```diff
@@ -139,11 +139,11 @@
     } else {
         $meta_source = "
           <span>Translate with:</span>
-          <a href='http://translate.google.com/#{$locale1_short_code}/{$locale2_short_code}/"
+          <a href='https://translate.google.com/#{$locale1_short_code}/{$locale2_short_code}/"
           // We use html_entity_decode twice because we can have strings as &amp;amp; stored
           . urlencode(strip_tags(html_entity_decode(html_entity_decode($source_string))))
           . "' target='_blank'>Google</a>
-          <a href='http://www.bing.com/translator/?from={$locale1_short_code}&to={$locale2_short_code}&text="
+          <a href='https//www.bing.com/translator/?from={$locale1_short_code}&to={$locale2_short_code}&text="
```
Comment (TheoChevalier) [inline app/views/results_entities.php]: hum, https:// ;)
